<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 Interpretacion de coeficientes | Random Intercept Cross-Lagged Panel Model</title>
  <meta name="description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="4 Interpretacion de coeficientes | Random Intercept Cross-Lagged Panel Model" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 Interpretacion de coeficientes | Random Intercept Cross-Lagged Panel Model" />
  
  <meta name="twitter:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="-" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="nestedm.html"/>
<link rel="next" href="referencias.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script>
  function unrolltab(evt, tabName) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
      tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
      tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(tabName).style.display = "block";
    evt.currentTarget.className += " active";
  }
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">RICLPM</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="1" data-path="modelo.html"><a href="modelo.html"><i class="fa fa-check"></i><b>1</b> Modelo</a></li>
<li class="chapter" data-level="2" data-path="estimacion.html"><a href="estimacion.html"><i class="fa fa-check"></i><b>2</b> Estimacion</a>
<ul>
<li class="chapter" data-level="2.1" data-path="estimacion.html"><a href="estimacion.html#sintaxis"><i class="fa fa-check"></i><b>2.1</b> Sintaxis</a></li>
<li class="chapter" data-level="2.2" data-path="estimacion.html"><a href="estimacion.html#modelo-basico"><i class="fa fa-check"></i><b>2.2</b> Modelo basico</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="nestedm.html"><a href="nestedm.html"><i class="fa fa-check"></i><b>3</b> Modelos anidados</a>
<ul>
<li class="chapter" data-level="3.0.1" data-path="nestedm.html"><a href="nestedm.html#sintaxis-constraints"><i class="fa fa-check"></i><b>3.0.1</b> Sintaxis constraints</a></li>
<li class="chapter" data-level="3.1" data-path="nestedm.html"><a href="nestedm.html#indicadores-de-bondad-de-ajuste"><i class="fa fa-check"></i><b>3.1</b> Indicadores de bondad de ajuste</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="nestedm.html"><a href="nestedm.html#extraccion"><i class="fa fa-check"></i><b>3.1.1</b> Extraccion</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="nestedm.html"><a href="nestedm.html#comparacion-de-bondad-de-ajuste"><i class="fa fa-check"></i><b>3.2</b> Comparacion de bondad de ajuste</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="interpretacion-de-coeficientes.html"><a href="interpretacion-de-coeficientes.html"><i class="fa fa-check"></i><b>4</b> Interpretacion de coeficientes</a>
<ul>
<li class="chapter" data-level="4.1" data-path="interpretacion-de-coeficientes.html"><a href="interpretacion-de-coeficientes.html#componente-between"><i class="fa fa-check"></i><b>4.1</b> Componente Between</a></li>
<li class="chapter" data-level="4.2" data-path="interpretacion-de-coeficientes.html"><a href="interpretacion-de-coeficientes.html#componente-within"><i class="fa fa-check"></i><b>4.2</b> Componente Within</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i><b>5</b> Referencias</a></li>
<li class="divider"></li>
<li style="text-align:center;" xmlns:dct="http://purl.org/dc/terms/" xmlns:cc="http://creativecommons.org/ns#"><a href="https://bookdown.org" target="_blank">Creado con bookdown</a> <a href="https://creativecommons.org/licenses/by-nc-sa/4.0"><img style="height:22px!important;margin-left: 3px;vertical-align:text-bottom;" src="https://search.creativecommons.org/static/img/cc_icon.svg" /><img  style="height:22px!important;margin-left: 3px;vertical-align:text-bottom;" src="https://search.creativecommons.org/static/img/cc-by_icon.svg" /><img  style="height:22px!important;margin-left: 3px;vertical-align:text-bottom;" src="https://search.creativecommons.org/static/img/cc-nc_icon.svg" /><img  style="height:22px!important;margin-left: 3px;vertical-align:text-bottom;" src="https://search.creativecommons.org/static/img/cc-sa_icon.svg" /></a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Random Intercept Cross-Lagged Panel Model</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="interpretacion-de-coeficientes" class="section level1" number="4">
<h1><span class="header-section-number">4</span> Interpretacion de coeficientes</h1>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="interpretacion-de-coeficientes.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">screenreg</span>(fit[[<span class="dv">8</span>]], <span class="at">type =</span> <span class="st">&quot;un&quot;</span>,</span>
<span id="cb37-2"><a href="interpretacion-de-coeficientes.html#cb37-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">params =</span> <span class="fu">c</span>(<span class="st">&quot;regression&quot;</span>,<span class="st">&quot;undirected&quot;</span>,<span class="st">&quot;variability&quot;</span>),</span>
<span id="cb37-3"><a href="interpretacion-de-coeficientes.html#cb37-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">summaries =</span> <span class="fu">c</span>(<span class="st">&quot;ChiSqM_Value&quot;</span>, <span class="st">&quot;ChiSqM_PValue&quot;</span>,</span>
<span id="cb37-4"><a href="interpretacion-de-coeficientes.html#cb37-4" aria-hidden="true" tabindex="-1"></a>                        <span class="st">&quot;CFI&quot;</span>, <span class="st">&quot;TLI&quot;</span>, <span class="st">&quot;RMSEA_Estimate&quot;</span>,</span>
<span id="cb37-5"><a href="interpretacion-de-coeficientes.html#cb37-5" aria-hidden="true" tabindex="-1"></a>                        <span class="st">&quot;Observations&quot;</span>), </span>
<span id="cb37-6"><a href="interpretacion-de-coeficientes.html#cb37-6" aria-hidden="true" tabindex="-1"></a>          <span class="co"># custom.header   = list(&quot;RICLPM&quot;=1),</span></span>
<span id="cb37-7"><a href="interpretacion-de-coeficientes.html#cb37-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">custom.model.names =</span> <span class="fu">c</span>(<span class="st">&quot;RICLPM bidireccional constrenido&quot;</span>),</span>
<span id="cb37-8"><a href="interpretacion-de-coeficientes.html#cb37-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">digits =</span> <span class="dv">3</span>, <span class="at">single.row=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
## ======================================================
##                       RICLPM bidireccional constrenido
## ------------------------------------------------------
##  CX2&lt;-CX1                0.155 (0.025) ***            
##  CX2&lt;-CY1                0.013 (0.011)                
##  CX3&lt;-CX2                0.155 (0.025) ***            
##  CX3&lt;-CY2                0.013 (0.011)                
##  CX4&lt;-CX3                0.155 (0.025) ***            
##  CX4&lt;-CY3                0.013 (0.011)                
##  CX5&lt;-CX4                0.155 (0.025) ***            
##  CX5&lt;-CY4                0.013 (0.011)                
##  CY2&lt;-CX1                0.061 (0.026) *              
##  CY2&lt;-CY1                0.142 (0.023) ***            
##  CY3&lt;-CX2                0.061 (0.026) *              
##  CY3&lt;-CY2                0.142 (0.023) ***            
##  CY4&lt;-CX3                0.061 (0.026) *              
##  CY4&lt;-CY3                0.142 (0.023) ***            
##  CY5&lt;-CX4                0.061 (0.026) *              
##  CY5&lt;-CY4                0.142 (0.023) ***            
##  CX1&lt;-&gt;CY1               0.177 (0.022) ***            
##  CX2&lt;-&gt;CY2               0.134 (0.018) ***            
##  CX3&lt;-&gt;CY3               0.061 (0.016) ***            
##  CX4&lt;-&gt;CY4               0.222 (0.029) ***            
##  CX5&lt;-&gt;CY5               0.008 (0.017)                
##  RI_X&lt;-&gt;RI_Y             0.186 (0.017) ***            
##  RI_X&lt;-&gt;CX1              0.000 (0.000)                
##  RI_X&lt;-&gt;CY1              0.000 (0.000)                
##  RI_Y&lt;-&gt;CX1              0.000 (0.000)                
##  RI_Y&lt;-&gt;CY1              0.000 (0.000)                
##  RI_X&lt;-&gt;RI_X             0.141 (0.017) ***            
##  RI_Y&lt;-&gt;RI_Y             0.548 (0.028) ***            
##  CX1&lt;-&gt;CX1               0.439 (0.028) ***            
##  CY1&lt;-&gt;CY1               0.876 (0.037) ***            
##  MARCHW01&lt;-&gt;MARCHW01     0.000 (0.000)                
##  MARCHW02&lt;-&gt;MARCHW02     0.000 (0.000)                
##  MARCHW03&lt;-&gt;MARCHW03     0.000 (0.000)                
##  MARCHW04&lt;-&gt;MARCHW04     0.000 (0.000)                
##  MARCHW05&lt;-&gt;MARCHW05     0.000 (0.000)                
##  REDESW01&lt;-&gt;REDESW01     0.000 (0.000)                
##  REDESW02&lt;-&gt;REDESW02     0.000 (0.000)                
##  REDESW03&lt;-&gt;REDESW03     0.000 (0.000)                
##  REDESW04&lt;-&gt;REDESW04     0.000 (0.000)                
##  REDESW05&lt;-&gt;REDESW05     0.000 (0.000)                
##  CX2&lt;-&gt;CX2               0.278 (0.021) ***            
##  CX3&lt;-&gt;CX3               0.214 (0.020) ***            
##  CX4&lt;-&gt;CX4               0.715 (0.037) ***            
##  CX5&lt;-&gt;CX5               0.276 (0.024) ***            
##  CY2&lt;-&gt;CY2               0.733 (0.036) ***            
##  CY3&lt;-&gt;CY3               0.578 (0.032) ***            
##  CY4&lt;-&gt;CY4               0.900 (0.041) ***            
##  CY5&lt;-&gt;CY5               0.734 (0.038) ***            
## ------------------------------------------------------
## ChiSqM_Value           195.387                        
## ChiSqM_PValue            0.000                        
## CFI                      0.955                        
## TLI                      0.938                        
## RMSEA_Estimate           0.041                        
## Observations          2927                            
## ======================================================
## *** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
<div class="figure" style="text-align: center"><span id="fig:resultados"></span>
<img src="images/RICLPM_resultados.png" alt="RI-CLPM full bidireccional constreñido para Participación Offline y Participación On-line" width="80%" />
<p class="caption">
Figura 4.1: RI-CLPM full bidireccional constreñido para Participación Offline y Participación On-line
</p>
</div>
<div id="componente-between" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Componente Between</h2>
<p>Ambos interceptos aleatorios tienen una varianza significativa. Esto implica que hay diferencias estables, entre individuos, respecto a sus puntajes esperados en participacion off-line y on-line.</p>
<p>Si la varianza no fuera distinta de 0, querria decir que han muy poca diferencias estables entre unidades y que cada individuo fluctua en torno a la misma gran media en el tiempo.</p>
<p>La covarianza entre los interceptos aleatorios es significativa (<span class="math inline">\(.186, SE=.017\)</span>), lo que sugiere que los individuos que tienen una alta participacion online tambien tienen una alta participacion off-line.</p>
</div>
<div id="componente-within" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> Componente Within</h2>
<p>Recordemos que los componentes <em>within</em> representan las desviaciones temporales en <span class="math inline">\(t\)</span> del individuo <span class="math inline">\(i\)</span> respecto a sus puntajes esperados (rasgos estables).</p>
<p>Los efectos autorregresivos tanto para participacion off-line como para participacion online son significativos (Off-line: <span class="math inline">\(\alpha_{t}=0.155; SE=.025\)</span> On-line: <span class="math inline">\(\gamma_{t}=0.142; SE=.023\)</span>). Los coeficientes indican el grado en el cual una variable continua incrementandose, en terminos de cambio individual, habiendo controlado por las caracteristicas individuales estables. De esta manera una desviacion de un punto sobre el nivel promedio de los individuos en participacion off-line persiste en la siguiente medicion como una desviacion positiva de 0.155 puntos respecto a su puntaje esperado. En el caso de la participacion on-line, una desviacion de un punto sobre el nivel promedio individual persiste durante la siguiente medicion como una desviacion positiva de 0.142 puntos sobre el nivel promedio individual.</p>
<p>Los efectos cross-lagged nos muestran que existe un efecto longitudinal intra-individuo de la participacion off-line sobre la participacion on-line (<span class="math inline">\(\gamma_{t}=0.061; SE=0.026\)</span>), pero no hay evidencia de que exista un efecto longitudinal de la participacion on-line sobre la participacion off-line.</p>
<p>Siendo asi, se observa que una desviacion de un punto sobre el nivel promedio de los individuos en participacion off-line predice una desviacion positiva de 0.061 puntos en la participacion on-line durante la siguiente medicion, controlando por las desviaciones respecto al puntaje esperado en participacion on-line.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="nestedm.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="referencias.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section",
"scroll_highlight": true
},
"search": true,
"info": false
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
